### ISSUE TITLE
unity 씬에 현재 위치 지도를 띄울 수있나요?

### ISSUE THREAD

**Issue by kimsijin33** [gouz7514/NavigationPractice#1]
스마트 폰의 현재 위치를 띄우려면 어떻게 해야하나요?

**Comment by gouz7514** [comment]
안녕하세요 지금 확인해서 답변 드립니다!
[MainActivity.java](https://github.com/gouz7514/NavigationPractice/blob/master/app/src/main/java/com/example/myapplication/MainActivity.java)
mapbox에서 제공하는 LocationEngine을 통해 현재 위치를 받아올 수 있습니다.

자세한 내용은 mapbox 공식 document를 참고하시면 도움될 것 같습니다.
링크 : [https://docs.mapbox.com/android/navigation/guides/device-location/](https://docs.mapbox.com/android/navigation/guides/device-location/)

**Comment by ijs5252** [comment]
혹시 unity파일 열람 가능할까요?
